<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-EJKEMI8" ignored="0" name="InterfaceFrame" tests="4" failures="2" timestamp="04 七月 2020 10:24:18 GMT" time="1.75" errors="0">
  <testcase name="Test" time="0.562" classname="com.cases.demo"/>
  <testcase name="Test" time="0.047" classname="com.cases.demo">
    <failure type="java.lang.AssertionError" message="expected [登录成功] but found [注册失败：用户名已存在]">
      <![CDATA[java.lang.AssertionError: expected [登录成功] but found [注册失败：用户名已存在]
at com.cases.demo.Test(demo.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
  <testcase name="Test" time="0.11" classname="com.cases.demo"/>
  <testcase name="Test" time="0.109" classname="com.cases.demo">
    <failure type="java.lang.AssertionError" message="expected [成功] but found [查询成功]">
      <![CDATA[java.lang.AssertionError: expected [成功] but found [查询成功]
at com.cases.demo.Test(demo.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
</testsuite> <!-- InterfaceFrame -->
